[package]
name = "rust_hangman"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
random_word = { version = "0.4.3", features = ["en"] }
